name: poligrapher
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyyaml=6.0
  - requests-cache=0.9.8
  - requests=2.32.4
  - spacy=3.8.7
  - spacy-model-en_core_web_md=3.8.0
  - regex=2024.11.6
  - psycopg2=2.9.10
  - pip
  - pip:
      - gradio==5.38.0
      - pandas==2.3.0
      - networkx==3.5
      - matplotlib==3.10.3
      - beautifulsoup4==4.13.4
      - langdetect==1.0.9
      - playwright==1.45.0
      - pymupdf4llm==0.0.27
      - markdown==3.8.2
      - toml==0.10.2
      - setfit
      - anytree==2.13.0
      - Unidecode==1.3.6
      - httpx==0.24.1
