name: poligrapher
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytest
  - pytest-cov
  - huggingface_hub=0.24.0 
  - pyyaml=6.0
  - requests=2.32.4
  - requests-cache=0.9.8
  - spacy=3.5.3
  - spacy-model-en_core_web_md=3.5.0
  - spacy-transformers=1.2.4
  - sentence-transformers=2.2.2
  - regex=2024.11.6
  - psycopg2=2.9.10
  - lxml=6.0.0
  - gradio=3.48.0
  - pandas=2.3.0
  - networkx=3.5
  - matplotlib=3.10.3
  - pillow=10.4.*
  - beautifulsoup4=4.13.4
  - langdetect=1.0.9
  - scikit-learn=1.2.1
  - toml=0.10.2
  - setfit=0.7.0
  - anytree=2.13.0
  - unidecode=1.3.6
  - httpx=0.24.1
  - markdown=3.8.2
  - pip
  - pip:
      - playwright==1.45.0
      - pymupdf4llm==0.0.27
